from governance.loader import GovernanceLoader
from governance.authority import (
    ActorResponsibilityBoundary,
    AuthorityActorClass,
    AuthorityCapability,
    AuthorityControlLevel,
    AuthorityDefinition,
    AuthorityDelegationRule,
    AuthorityExercise,
    AuthorityModelCapability,
    AuthorityProvenance,
    AuthorityReviewStatus,
    AuthorityType,
    GuardianAuthorityModel,
    GuardianAuthorityModelValidator,
    GuardianAuthorityValidationError,
    ProhibitedAuthorityCombination,
)
from governance.provider_authorization import (
    AuthorizationDecisionEvidence,
    AuthorizationDecisionType,
    AuthorizationExpirationEvidence,
    AuthorizationRestorationEvidence,
    AuthorizationRevocationEvidence,
    AuthorizationSuspensionEvidence,
    AuthorizationUncertaintyStatus,
    DecidingActorReference,
    GuardianProviderAuthorizationPackage,
    GuardianProviderAuthorizationValidator,
    ProviderAuthorizationGrant,
    ProviderAuthorizationPackageCapability,
    ProviderAuthorizationResolutionSnapshot,
    ProviderAuthorizationStatus,
    ProviderAuthorizationValidationError,
    ProviderIdentity,
    ProviderIdentityVerificationStatus,
    ProviderType,
)
from governance.b2_provider_identity import (
    B2CapabilityDescriptor,
    B2GovernanceDecisionId,
    B2InstitutionalSourceId,
    B2NonPersonalReferenceId,
    B2ProviderClass,
    B2ProviderIdentity,
    B2ProviderIdentityId,
    B2ProviderProvenance,
    B2RegistrationBasisReference,
    B2ResponsibilityArea,
)
from governance.capability_invocation import (
    ALLOWED_INVOCATION_OPERATION_MODES,
    NON_EXECUTING_INVOCATION_CAPABILITIES,
    REQUIRED_INVOCATION_CHECKS,
    CapabilityInvocationDecision,
    CapabilityInvocationEvidence,
    CapabilityInvocationPackageCapability,
    CapabilityInvocationReceipt,
    CapabilityInvocationRequest,
    CapabilityInvocationResolutionSnapshot,
    CapabilityInvocationValidationError,
    GuardianCapabilityInvocationBoundary,
    GuardianCapabilityInvocationValidator,
    InvocationCheck,
    InvocationContextBinding,
    InvocationContextBindingType,
    InvocationDataScope,
    InvocationDecisionReason,
    InvocationDecisionStatus,
    InvocationOperationMode,
    InvocationReceiptValidationStatus,
)
from governance.read_only_b1_runtime import (
    B1ReadOnlyProviderAdapter,
    B1ReadOnlyRuntimeExecutor,
    B1RuntimeExecutionEnvelope,
    B1RuntimeExecutionOutcome,
    B1RuntimeExecutionRequest,
    B1RuntimeExecutionRequestValidator,
    B1RuntimeOutputValidator,
    B1RuntimeResult,
    B1RuntimeValidationError,
    ProviderAdapterRequest,
    ProviderAdapterResult,
    ProviderOutputKind,
    ProviderTechnicalStatus,
    RuntimeBlockReason,
    RuntimeCheck,
    RuntimeDataField,
    RuntimeExecutionEvidence,
    RuntimeExecutionReceipt,
    RuntimeExecutionStatus,
    RuntimeOutputContract,
    RuntimeProvisionStatus,
    RuntimeRecordMetadata,
)
from governance.runtime_incident import (
    EXPECTED_INCIDENT_SEVERITY,
    READ_ONLY_B1_RUNTIME_REFERENCE,
    RuntimeIncidentEvidence,
    RuntimeIncidentPackage,
    RuntimeIncidentSeverity,
    RuntimeIncidentSnapshot,
    RuntimeIncidentSnapshotStatus,
    RuntimeIncidentType,
    RuntimeIncidentValidationError,
    RuntimeIncidentValidator,
    RuntimeNoIncidentEvidence,
)
from governance.runtime_observation import (
    GOVERNANCE_PROFILE_ACTORS,
    PROHIBITED_USER_OBSERVATION_CATEGORIES,
    RUNTIME_EVENT_CATEGORIES,
    SYSTEM_OBSERVATION_CATEGORIES,
    ObservationProfileApprovalStatus,
    ObservationSnapshotStatus,
    RuntimeObservationCategory,
    RuntimeObservationEvent,
    RuntimeObservationGovernance,
    RuntimeObservationGovernanceValidationError,
    RuntimeObservationGovernanceValidator,
    RuntimeObservationProfile,
    RuntimeObservationScope,
    RuntimeObservationSnapshot,
)
from governance.runtime_audit import (
    PROHIBITED_USER_AUDIT_SUBJECTS,
    SYSTEM_AUDIT_SUBJECTS,
    RuntimeAuditCheck,
    RuntimeAuditCompletenessLevel,
    RuntimeAuditCompletenessStatus,
    RuntimeAuditEvidence,
    RuntimeAuditEvidenceType,
    RuntimeAuditPackage,
    RuntimeAuditProfile,
    RuntimeAuditProfileChangeActor,
    RuntimeAuditResolutionSnapshot,
    RuntimeAuditResult,
    RuntimeAuditScope,
    RuntimeAuditSubject,
    RuntimeAuditTimeBoundary,
    RuntimeAuditValidationError,
    RuntimeAuditValidator,
)
from governance.operational_memory import (
    OperationalMemoryArtifact,
    OperationalMemoryArtifactBinding,
    OperationalMemoryArtifactType,
    OperationalMemoryOrigin,
    OperationalMemoryPackage,
    OperationalMemoryRecord,
    OperationalMemorySnapshot,
    OperationalMemoryValidationError,
    OperationalMemoryValidator,
)
from governance.physical_operational_persistence import (
    PersistencePortOperation,
    PersistencePortRequest,
    PersistencePortResult,
    PersistencePortResultStatus,
    PhysicalBackupContract,
    PhysicalBackupStatus,
    PhysicalCompletenessStatus,
    PhysicalOperationalPersistencePackage,
    PhysicalOperationalPersistencePort,
    PhysicalOperationalPersistenceSnapshot,
    PhysicalOperationalPersistenceValidationError,
    PhysicalOperationalPersistenceValidator,
    PhysicalPersistenceRecord,
    PhysicalPersistenceStatus,
    PhysicalRecoveryContract,
    PhysicalRecoveryStatus,
)
from governance.operational_metrics_notifications import (
    OperationalMetricAggregationRule,
    OperationalMetricDefinition,
    OperationalMetricObservation,
    OperationalMetricPackage,
    OperationalMetricSnapshot,
    OperationalMetricUnit,
    OperationalMetricUncertaintyStatus,
    OperationalMetricValidationError,
    OperationalMetricValidator,
    OperationalNotificationDecisionStatus,
    OperationalNotificationDeliveryStatus,
    OperationalNotificationEvidence,
    OperationalNotificationExcludedContent,
    OperationalNotificationMessageType,
    OperationalNotificationPackage,
    OperationalNotificationPolicy,
    OperationalNotificationRecipientCategory,
    OperationalNotificationSeverity,
    OperationalNotificationSnapshot,
    OperationalNotificationSourceType,
    OperationalNotificationTriggerCondition,
    OperationalNotificationTriggerReason,
    OperationalNotificationValidationError,
    OperationalNotificationValidator,
)
from governance.models import (
    GovernanceBody,
    GovernanceContext,
    NormLevel,
    ProtectionGoal,
    TrustDomain,
)

__all__ = [
    "B2_AUTHORIZATION_CONTRACT_VERSION",
    "REQUIRED_B2_AUTHORITY_BASIS",
    "B2AAVBinding",
    "B2AuthorizationDecision",
    "B2AuthorizationEvaluationEvidence",
    "B2AuthorizationEvaluator",
    "B2AuthorizationProvenance",
    "B2AuthorizationReason",
    "B2AuthorizationStructureError",
    "B2Authority",
    "B2AuthorityClass",
    "B2AuthorityId",
    "B2ConstitutionalBasis",
    "B2D3Consent",
    "B2EvaluationEvidence",
    "B2Grant",
    "B2InstitutionalScope",
    "B2NegativeGovernanceEvidence",
    "B2PurposeScope",
    "B2T4GrantReceipt",
    "B2UODLBinding",
    "B2UODLOperation",
    "B2_PURPOSE_UODL_BINDING_CONTRACT_VERSION",
    "B2BindingEvaluationOutcome",
    "B2BindingObservationScope",
    "B2BindingProvenance",
    "B2CorridorPurposeReference",
    "B2PurposeBinding",
    "B2PurposeBindingEvidence",
    "B2PurposeBindingId",
    "B2PurposeBindingRule",
    "B2PurposeBindingValidator",
    "B2PurposeComparisonRelation",
    "B2PurposeUODLBindingFoundation",
    "B2PurposeUODLBindingFoundationValidator",
    "B2PurposeUODLBindingValidationError",
    "B2UODLLayerRelation",
    "B2UODLMapping",
    "B2UODLMappingEvidence",
    "B2UODLMappingId",
    "B2UODLMappingValidator",
    "B2UODLPairRule",
    "B2_CAPABILITY_INVOCATION_CONTRACT_VERSION",
    "B2CapabilityInvocationAssertion",
    "B2CapabilityInvocationBinding",
    "B2CapabilityInvocationBindingId",
    "B2CapabilityInvocationDecision",
    "B2CapabilityInvocationDecisionId",
    "B2CapabilityInvocationDecisionResult",
    "B2CapabilityInvocationEvaluator",
    "B2CapabilityInvocationEvidence",
    "B2CapabilityInvocationEvidenceId",
    "B2CapabilityInvocationFoundation",
    "B2CapabilityInvocationFoundationValidator",
    "B2CapabilityInvocationIntent",
    "B2CapabilityInvocationObservationScope",
    "B2CapabilityInvocationReceipt",
    "B2CapabilityInvocationReceiptId",
    "B2CapabilityInvocationRequest",
    "B2CapabilityInvocationRequestId",
    "B2CapabilityInvocationResolutionSnapshot",
    "B2CapabilityInvocationResolutionSnapshotId",
    "B2CapabilityInvocationValidationError",
    "B2CapabilityInvocationValidator",
    "B2CapabilityInvocationViolation",
    "GOVERNANCE_DECISION_INCIDENT_CONTRACT_VERSION",
    "GOVERNANCE_DECISION_RECORD_DIRECTORY",
    "GOVERNANCE_INCIDENT_EVIDENCE_DIRECTORY",
    "GovernanceCanonicalArtifactReference",
    "GovernanceCorrectionAction",
    "GovernanceCorrectionStep",
    "GovernanceCorrectionStepState",
    "GovernanceCustodyReferenceValidator",
    "GovernanceDecisionClass",
    "GovernanceDecisionId",
    "GovernanceDecisionRecord",
    "GovernanceDecisionRecordValidator",
    "GovernanceDeviationCode",
    "GovernanceDocumentationState",
    "GovernanceEvidencePrimitiveValidator",
    "GovernanceEvidenceReference",
    "GovernanceEvidenceType",
    "GovernanceEvidenceValidator",
    "GovernanceHistoricalTimeState",
    "GovernanceImpactCode",
    "GovernanceIncidentClass",
    "GovernanceIncidentEvidence",
    "GovernanceIncidentEvidenceValidator",
    "GovernanceIncidentClassificationValidator",
    "GovernanceIncidentId",
    "GovernanceInstitutionalRole",
    "GovernanceKnownTime",
    "GovernanceOpenDecisionQuestion",
    "GovernanceOpenDecisionQuestionValidator",
    "GovernanceOpenQuestionClass",
    "GovernanceProvenance",
    "GovernanceProvenanceArtifactClass",
    "GovernanceProvenanceContext",
    "GovernanceProvenanceId",
    "GovernanceProvenanceValidator",
    "GovernanceRoleDecisionValidator",
    "GovernanceScopeEntry",
    "GovernanceScopeType",
    "GovernanceScopeValidator",
    "GovernanceSectionReference",
    "GovernanceStatementScope",
    "GovernanceStep",
    "GovernanceStepSequenceValidator",
    "GovernanceSubjectReference",
    "GovernanceTimeValidator",
    "MissingGovernanceEvidence",
    "MissingGovernanceEvidenceStatus",
    "MissingGovernanceEvidenceType",
    "MissingGovernanceEvidenceValidator",
    "B2CapabilityDescriptor",
    "B2GovernanceDecisionId",
    "B2InstitutionalSourceId",
    "B2NonPersonalReferenceId",
    "B2ProviderClass",
    "B2ProviderIdentity",
    "B2ProviderIdentityId",
    "B2ProviderProvenance",
    "B2RegistrationBasisReference",
    "B2ResponsibilityArea",
    "B2_PROVIDER_AUTHORIZATION_CONTRACT_VERSION",
    "B2AuthorizationFoundation",
    "B2AuthorizationFoundationValidator",
    "B2ProviderAuthorization",
    "B2ProviderAuthorizationEvaluationEvidence",
    "B2ProviderAuthorizationEvaluator",
    "B2ProviderAuthorizationEvidence",
    "B2ProviderAuthorizationId",
    "B2ProviderAuthorizationNegativeGovernanceEvidence",
    "B2ProviderAuthorizationProvenance",
    "B2ProviderAuthorizationReason",
    "B2ProviderAuthorizationValidationError",
    "B2ProviderAuthorizationValidator",
    "ALLOWED_B2_DATA_CLASSES",
    "ALLOWED_B2_DATA_FLOWS",
    "ALLOWED_B2_DATA_SOURCES",
    "B2ConsentBoundary",
    "B2ConsentRequirement",
    "B2ConsentUse",
    "B2DataClass",
    "B2DataClassification",
    "B2DataCorridor",
    "B2DataCorridorPackage",
    "B2DataCorridorSnapshot",
    "B2DataCorridorValidationError",
    "B2DataCorridorValidator",
    "B2DataFlowDirection",
    "B2DataRuleReference",
    "B2DataSensitivity",
    "B2DataSource",
    "B2DepersonalizationBoundary",
    "B2NegativeCorridorRules",
    "B2ProhibitedCombination",
    "B2ProhibitedDestination",
    "B2ProhibitedPurposeChange",
    "B2ProhibitedUse",
    "B2ResidualIdentifier",
    "D1_D6_REFERENCES",
    "D3_REFERENCE",
    "PROHIBITED_B2_DATA_CLASSES",
    "PROHIBITED_B2_DATA_FLOWS",
    "PROHIBITED_B2_DATA_SOURCES",
    "PROHIBITED_RESIDUAL_IDENTIFIERS",
    "REQUIRED_D3_BINDINGS",
    "REQUIRED_PROHIBITED_USES",
    "ActorResponsibilityBoundary",
    "ALLOWED_INVOCATION_OPERATION_MODES",
    "AuthorizationDecisionEvidence",
    "AuthorizationDecisionType",
    "AuthorizationExpirationEvidence",
    "AuthorizationRestorationEvidence",
    "AuthorizationRevocationEvidence",
    "AuthorizationSuspensionEvidence",
    "AuthorizationUncertaintyStatus",
    "CapabilityInvocationDecision",
    "CapabilityInvocationEvidence",
    "CapabilityInvocationPackageCapability",
    "CapabilityInvocationReceipt",
    "CapabilityInvocationRequest",
    "CapabilityInvocationResolutionSnapshot",
    "CapabilityInvocationValidationError",
    "B1ReadOnlyProviderAdapter",
    "B1ReadOnlyRuntimeExecutor",
    "B1RuntimeExecutionEnvelope",
    "B1RuntimeExecutionOutcome",
    "B1RuntimeExecutionRequest",
    "B1RuntimeExecutionRequestValidator",
    "B1RuntimeOutputValidator",
    "B1RuntimeResult",
    "B1RuntimeValidationError",
    "AuthorityActorClass",
    "AuthorityCapability",
    "AuthorityControlLevel",
    "AuthorityDefinition",
    "AuthorityDelegationRule",
    "AuthorityExercise",
    "AuthorityModelCapability",
    "AuthorityProvenance",
    "AuthorityReviewStatus",
    "AuthorityType",
    "DecidingActorReference",
    "GovernanceBody",
    "GovernanceContext",
    "GovernanceLoader",
    "GuardianAuthorityModel",
    "GuardianAuthorityModelValidator",
    "GuardianAuthorityValidationError",
    "GuardianCapabilityInvocationBoundary",
    "GuardianCapabilityInvocationValidator",
    "GuardianProviderAuthorizationPackage",
    "GuardianProviderAuthorizationValidator",
    "NormLevel",
    "NON_EXECUTING_INVOCATION_CAPABILITIES",
    "ProhibitedAuthorityCombination",
    "ProviderAuthorizationGrant",
    "ProviderAuthorizationPackageCapability",
    "ProviderAuthorizationResolutionSnapshot",
    "ProviderAuthorizationStatus",
    "ProviderAuthorizationValidationError",
    "ProviderIdentity",
    "ProviderIdentityVerificationStatus",
    "ProviderType",
    "ProviderAdapterRequest",
    "ProviderAdapterResult",
    "ProviderOutputKind",
    "ProviderTechnicalStatus",
    "REQUIRED_INVOCATION_CHECKS",
    "InvocationCheck",
    "InvocationContextBinding",
    "InvocationContextBindingType",
    "InvocationDataScope",
    "InvocationDecisionReason",
    "InvocationDecisionStatus",
    "InvocationOperationMode",
    "InvocationReceiptValidationStatus",
    "RuntimeBlockReason",
    "RuntimeCheck",
    "RuntimeDataField",
    "RuntimeExecutionEvidence",
    "RuntimeExecutionReceipt",
    "RuntimeExecutionStatus",
    "RuntimeIncidentEvidence",
    "RuntimeIncidentPackage",
    "RuntimeIncidentSeverity",
    "RuntimeIncidentSnapshot",
    "RuntimeIncidentSnapshotStatus",
    "RuntimeIncidentType",
    "RuntimeIncidentValidationError",
    "RuntimeIncidentValidator",
    "RuntimeNoIncidentEvidence",
    "RuntimeAuditCheck",
    "RuntimeAuditCompletenessLevel",
    "RuntimeAuditCompletenessStatus",
    "RuntimeAuditEvidence",
    "RuntimeAuditEvidenceType",
    "RuntimeAuditPackage",
    "RuntimeAuditProfile",
    "RuntimeAuditProfileChangeActor",
    "RuntimeAuditResolutionSnapshot",
    "RuntimeAuditResult",
    "RuntimeAuditScope",
    "RuntimeAuditSubject",
    "RuntimeAuditTimeBoundary",
    "RuntimeAuditValidationError",
    "RuntimeAuditValidator",
    "RuntimeObservationCategory",
    "RuntimeObservationEvent",
    "RuntimeObservationGovernance",
    "RuntimeObservationGovernanceValidationError",
    "RuntimeObservationGovernanceValidator",
    "RuntimeObservationProfile",
    "RuntimeObservationScope",
    "RuntimeObservationSnapshot",
    "RuntimeOutputContract",
    "RuntimeProvisionStatus",
    "RuntimeRecordMetadata",
    "ProtectionGoal",
    "TrustDomain",
    "EXPECTED_INCIDENT_SEVERITY",
    "GOVERNANCE_PROFILE_ACTORS",
    "ObservationProfileApprovalStatus",
    "ObservationSnapshotStatus",
    "OperationalMemoryArtifact",
    "OperationalMemoryArtifactBinding",
    "OperationalMemoryArtifactType",
    "OperationalMemoryOrigin",
    "OperationalMemoryPackage",
    "OperationalMemoryRecord",
    "OperationalMemorySnapshot",
    "OperationalMemoryValidationError",
    "OperationalMemoryValidator",
    "OperationalMetricAggregationRule",
    "OperationalMetricDefinition",
    "OperationalMetricObservation",
    "OperationalMetricPackage",
    "OperationalMetricSnapshot",
    "OperationalMetricUnit",
    "OperationalMetricUncertaintyStatus",
    "OperationalMetricValidationError",
    "OperationalMetricValidator",
    "OperationalNotificationDecisionStatus",
    "OperationalNotificationDeliveryStatus",
    "OperationalNotificationEvidence",
    "OperationalNotificationExcludedContent",
    "OperationalNotificationMessageType",
    "OperationalNotificationPackage",
    "OperationalNotificationPolicy",
    "OperationalNotificationRecipientCategory",
    "OperationalNotificationSeverity",
    "OperationalNotificationSnapshot",
    "OperationalNotificationSourceType",
    "OperationalNotificationTriggerCondition",
    "OperationalNotificationTriggerReason",
    "OperationalNotificationValidationError",
    "OperationalNotificationValidator",
    "PersistencePortOperation",
    "PersistencePortRequest",
    "PersistencePortResult",
    "PersistencePortResultStatus",
    "PhysicalBackupContract",
    "PhysicalBackupStatus",
    "PhysicalCompletenessStatus",
    "PhysicalOperationalPersistencePackage",
    "PhysicalOperationalPersistencePort",
    "PhysicalOperationalPersistenceSnapshot",
    "PhysicalOperationalPersistenceValidationError",
    "PhysicalOperationalPersistenceValidator",
    "PhysicalPersistenceRecord",
    "PhysicalPersistenceStatus",
    "PhysicalRecoveryContract",
    "PhysicalRecoveryStatus",
    "PROHIBITED_USER_OBSERVATION_CATEGORIES",
    "PROHIBITED_USER_AUDIT_SUBJECTS",
    "READ_ONLY_B1_RUNTIME_REFERENCE",
    "RUNTIME_EVENT_CATEGORIES",
    "SYSTEM_OBSERVATION_CATEGORIES",
    "SYSTEM_AUDIT_SUBJECTS",
]


_B2_AUTHORIZATION_EXPORTS = frozenset(
    {
        "B2_AUTHORIZATION_CONTRACT_VERSION",
        "REQUIRED_B2_AUTHORITY_BASIS",
        "B2AAVBinding",
        "B2AuthorizationDecision",
        "B2AuthorizationEvaluationEvidence",
        "B2AuthorizationEvaluator",
        "B2AuthorizationProvenance",
        "B2AuthorizationReason",
        "B2AuthorizationStructureError",
        "B2Authority",
        "B2AuthorityClass",
        "B2AuthorityId",
        "B2ConstitutionalBasis",
        "B2D3Consent",
        "B2EvaluationEvidence",
        "B2Grant",
        "B2InstitutionalScope",
        "B2NegativeGovernanceEvidence",
        "B2PurposeScope",
        "B2T4GrantReceipt",
        "B2UODLBinding",
        "B2UODLOperation",
    }
)


_B2_PROVIDER_AUTHORIZATION_EXPORTS = frozenset(
    {
        "B2_PROVIDER_AUTHORIZATION_CONTRACT_VERSION",
        "B2AuthorizationFoundation",
        "B2AuthorizationFoundationValidator",
        "B2ProviderAuthorization",
        "B2ProviderAuthorizationEvaluationEvidence",
        "B2ProviderAuthorizationEvaluator",
        "B2ProviderAuthorizationEvidence",
        "B2ProviderAuthorizationId",
        "B2ProviderAuthorizationNegativeGovernanceEvidence",
        "B2ProviderAuthorizationProvenance",
        "B2ProviderAuthorizationReason",
        "B2ProviderAuthorizationValidationError",
        "B2ProviderAuthorizationValidator",
    }
)


_B2_PURPOSE_UODL_BINDING_EXPORTS = frozenset(
    {
        "B2_PURPOSE_UODL_BINDING_CONTRACT_VERSION",
        "B2BindingEvaluationOutcome",
        "B2BindingObservationScope",
        "B2BindingProvenance",
        "B2CorridorPurposeReference",
        "B2PurposeBinding",
        "B2PurposeBindingEvidence",
        "B2PurposeBindingId",
        "B2PurposeBindingRule",
        "B2PurposeBindingValidator",
        "B2PurposeComparisonRelation",
        "B2PurposeUODLBindingFoundation",
        "B2PurposeUODLBindingFoundationValidator",
        "B2PurposeUODLBindingValidationError",
        "B2UODLLayerRelation",
        "B2UODLMapping",
        "B2UODLMappingEvidence",
        "B2UODLMappingId",
        "B2UODLMappingValidator",
        "B2UODLPairRule",
    }
)


_B2_CAPABILITY_INVOCATION_EXPORTS = frozenset(
    {
        "B2_CAPABILITY_INVOCATION_CONTRACT_VERSION",
        "B2CapabilityInvocationAssertion",
        "B2CapabilityInvocationBinding",
        "B2CapabilityInvocationBindingId",
        "B2CapabilityInvocationDecision",
        "B2CapabilityInvocationDecisionId",
        "B2CapabilityInvocationDecisionResult",
        "B2CapabilityInvocationEvaluator",
        "B2CapabilityInvocationEvidence",
        "B2CapabilityInvocationEvidenceId",
        "B2CapabilityInvocationFoundation",
        "B2CapabilityInvocationFoundationValidator",
        "B2CapabilityInvocationIntent",
        "B2CapabilityInvocationObservationScope",
        "B2CapabilityInvocationReceipt",
        "B2CapabilityInvocationReceiptId",
        "B2CapabilityInvocationRequest",
        "B2CapabilityInvocationRequestId",
        "B2CapabilityInvocationResolutionSnapshot",
        "B2CapabilityInvocationResolutionSnapshotId",
        "B2CapabilityInvocationValidationError",
        "B2CapabilityInvocationValidator",
        "B2CapabilityInvocationViolation",
    }
)


_GOVERNANCE_DECISION_INCIDENT_EXPORTS = frozenset(
    {
        "GOVERNANCE_DECISION_INCIDENT_CONTRACT_VERSION",
        "GOVERNANCE_DECISION_RECORD_DIRECTORY",
        "GOVERNANCE_INCIDENT_EVIDENCE_DIRECTORY",
        "GovernanceCanonicalArtifactReference",
        "GovernanceCorrectionAction",
        "GovernanceCorrectionStep",
        "GovernanceCorrectionStepState",
        "GovernanceCustodyReferenceValidator",
        "GovernanceDecisionClass",
        "GovernanceDecisionId",
        "GovernanceDecisionRecord",
        "GovernanceDecisionRecordValidator",
        "GovernanceDeviationCode",
        "GovernanceDocumentationState",
        "GovernanceEvidencePrimitiveValidator",
        "GovernanceEvidenceReference",
        "GovernanceEvidenceType",
        "GovernanceEvidenceValidator",
        "GovernanceHistoricalTimeState",
        "GovernanceImpactCode",
        "GovernanceIncidentClass",
        "GovernanceIncidentEvidence",
        "GovernanceIncidentEvidenceValidator",
        "GovernanceIncidentClassificationValidator",
        "GovernanceIncidentId",
        "GovernanceInstitutionalRole",
        "GovernanceKnownTime",
        "GovernanceOpenDecisionQuestion",
        "GovernanceOpenDecisionQuestionValidator",
        "GovernanceOpenQuestionClass",
        "GovernanceProvenance",
        "GovernanceProvenanceArtifactClass",
        "GovernanceProvenanceContext",
        "GovernanceProvenanceId",
        "GovernanceProvenanceValidator",
        "GovernanceRoleDecisionValidator",
        "GovernanceScopeEntry",
        "GovernanceScopeType",
        "GovernanceScopeValidator",
        "GovernanceSectionReference",
        "GovernanceStatementScope",
        "GovernanceStep",
        "GovernanceStepSequenceValidator",
        "GovernanceSubjectReference",
        "GovernanceTimeValidator",
        "MissingGovernanceEvidence",
        "MissingGovernanceEvidenceStatus",
        "MissingGovernanceEvidenceType",
        "MissingGovernanceEvidenceValidator",
    }
)


_B2_DATA_CORRIDOR_EXPORTS = frozenset(
    name
    for name in __all__
    if (
        name.startswith("B2")
        and name not in _B2_AUTHORIZATION_EXPORTS
        and name not in _B2_PROVIDER_AUTHORIZATION_EXPORTS
        and name not in _B2_PURPOSE_UODL_BINDING_EXPORTS
        and name not in _B2_CAPABILITY_INVOCATION_EXPORTS
        and name not in _GOVERNANCE_DECISION_INCIDENT_EXPORTS
    )
    or name.startswith("ALLOWED_B2_")
    or name.startswith("PROHIBITED_B2_")
    or name in {
        "D1_D6_REFERENCES",
        "D3_REFERENCE",
        "PROHIBITED_RESIDUAL_IDENTIFIERS",
        "REQUIRED_D3_BINDINGS",
        "REQUIRED_PROHIBITED_USES",
    }
)


def __getattr__(name):
    """Load the AAV/UODL-bound B2 API without creating an import cycle."""
    if name in _B2_AUTHORIZATION_EXPORTS:
        from governance import b2_authorization

        value = getattr(b2_authorization, name)
        globals()[name] = value
        return value
    if name in _B2_PROVIDER_AUTHORIZATION_EXPORTS:
        from governance import b2_provider_authorization

        value = getattr(b2_provider_authorization, name)
        globals()[name] = value
        return value
    if name in _B2_PURPOSE_UODL_BINDING_EXPORTS:
        from governance import b2_purpose_uodl_binding

        value = getattr(b2_purpose_uodl_binding, name)
        globals()[name] = value
        return value
    if name in _B2_CAPABILITY_INVOCATION_EXPORTS:
        from governance import b2_capability_invocation

        value = getattr(b2_capability_invocation, name)
        globals()[name] = value
        return value
    if name in _GOVERNANCE_DECISION_INCIDENT_EXPORTS:
        from governance import governance_decision_incident_evidence

        value = getattr(governance_decision_incident_evidence, name)
        globals()[name] = value
        return value
    if name in _B2_DATA_CORRIDOR_EXPORTS:
        from governance import b2_data_corridor

        value = getattr(b2_data_corridor, name)
        globals()[name] = value
        return value
    raise AttributeError("module 'governance' has no attribute {!r}".format(name))
