"""Guardian Understanding Core.

This package builds a transient, typed understanding of a user's words. It
does not decide, route, persist, or activate capabilities.
"""

from guardian_understanding.models import (
    Contradiction,
    Fact,
    FactStatus,
    Goal,
    GoalStatus,
    Hypothesis,
    HypothesisStatus,
    UnderstandingChange,
    UnderstandingOperation,
    UnderstandingOperationType,
    UnderstandingRevision,
    UnderstandingResult,
    UnderstandingState,
    UnderstandingUpdate,
    Unknown,
    UnknownStatus,
)
from guardian_understanding.service import GuardianUnderstandingService
from guardian_understanding.proposal import (
    GuardianUnderstandingProposalService,
    UnderstandingProposal,
    UnderstandingProposalApplication,
    UnderstandingProposalCandidate,
    UnderstandingProposalSelection,
    UnderstandingProposalSet,
)
from guardian_understanding.clarification import (
    ClarificationResolution,
    ClarificationResolutionRequest,
    ClarificationResolutionResult,
    ClarificationResolutionType,
    GuardianClarificationResolutionService,
    ProposalDisposition,
    ProposalDispositionType,
)
from guardian_understanding.answer_boundary import (
    ALWAYS_FORBIDDEN_CAPABILITIES,
    AnswerBoundaryContract,
    AnswerBoundaryValidationError,
    AnswerCapability,
    AnswerOperatingMode,
    ClassificationReference,
    GuardianAnswerBoundaryValidator,
    answer_mode_protection_level,
    most_protective_answer_mode,
)
from guardian_understanding.source_chain import (
    DeclaredSourceContradiction,
    GuardianAnswerContextReference,
    GuardianSourceChainContract,
    GuardianSourceChainValidator,
    SourceChainCapability,
    SourceChainReference,
    SourceChainValidationError,
    SourceKind,
    SourceProvenanceCategory,
    SourceRecheckKind,
    SourceRecheckRequirement,
    SourceUncertaintyStatus,
)
from guardian_understanding.classification import (
    ClassificationCapability,
    ClassificationProviderType,
    ClassificationReason,
    ClassificationUncertaintyStatus,
    ClassificationValidationError,
    GuardianClassificationContract,
    GuardianClassificationValidator,
)
from guardian_understanding.answer_foundation import (
    AnswerFoundationIntegrationError,
    GuardianAnswerFoundationIntegration,
    GuardianAnswerFoundationIntegrationValidator,
)

__all__ = [
    "Contradiction",
    "ClarificationResolution",
    "ClarificationResolutionRequest",
    "ClarificationResolutionResult",
    "ClarificationResolutionType",
    "Fact",
    "FactStatus",
    "Goal",
    "GoalStatus",
    "GuardianUnderstandingService",
    "GuardianUnderstandingProposalService",
    "GuardianClarificationResolutionService",
    "Hypothesis",
    "HypothesisStatus",
    "UnderstandingChange",
    "UnderstandingOperation",
    "UnderstandingOperationType",
    "UnderstandingProposal",
    "UnderstandingProposalApplication",
    "UnderstandingProposalCandidate",
    "UnderstandingProposalSelection",
    "UnderstandingProposalSet",
    "ProposalDisposition",
    "ProposalDispositionType",
    "UnderstandingRevision",
    "UnderstandingResult",
    "UnderstandingState",
    "UnderstandingUpdate",
    "Unknown",
    "UnknownStatus",
    "ALWAYS_FORBIDDEN_CAPABILITIES",
    "AnswerBoundaryContract",
    "AnswerBoundaryValidationError",
    "AnswerCapability",
    "AnswerOperatingMode",
    "ClassificationReference",
    "GuardianAnswerBoundaryValidator",
    "answer_mode_protection_level",
    "most_protective_answer_mode",
    "DeclaredSourceContradiction",
    "GuardianAnswerContextReference",
    "GuardianSourceChainContract",
    "GuardianSourceChainValidator",
    "SourceChainCapability",
    "SourceChainReference",
    "SourceChainValidationError",
    "SourceKind",
    "SourceProvenanceCategory",
    "SourceRecheckKind",
    "SourceRecheckRequirement",
    "SourceUncertaintyStatus",
    "ClassificationCapability",
    "ClassificationProviderType",
    "ClassificationReason",
    "ClassificationUncertaintyStatus",
    "ClassificationValidationError",
    "GuardianClassificationContract",
    "GuardianClassificationValidator",
    "AnswerFoundationIntegrationError",
    "GuardianAnswerFoundationIntegration",
    "GuardianAnswerFoundationIntegrationValidator",
]
